canonifyurls = true
title = "Water Data For The Nation Blog"
name = ["Laura DeCicco"]
email = ["r_admin@usgs.gov"]
preserveTaxonomyNames = true
paginate = 100
theme = "wdfn_theme"
[markup.goldmark.renderer]
  unsafe= true