canonifyurls = true
title = "Water Data For The Nation Blog"
name = ["Laura DeCicco"]
email = ["r_admin@usgs.gov"]
preserveTaxonomyNames = true
paginate = 100
theme = "wdfn_theme"
[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "manni"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe= true